version: '3'

services:
  # Контейнер с базой данных
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always