version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:${PG_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: