#version: '3'
#services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${PG_USERNAME}
#      POSTGRES_PASSWORD: ${PG_PASSWORD}
#      POSTGRES_DB: ${PG_DB_NAME}
#    ports:
#      - "5432:${PG_PORT}"
#    volumes:
#      - db_data:/var/lib/postgresql/data
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#volumes:
#  db_data:

version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: